"""added report and category tables

Revision ID: 39adb445aee6
Revises: e082f83a58d0
Create Date: 2024-03-20 08:07:51.090576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39adb445aee6'
down_revision: Union[str, None] = 'e082f83a58d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superusers_email'), 'superusers', ['email'], unique=True)
    op.create_index(op.f('ix_superusers_id'), 'superusers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_superusers_id'), table_name='superusers')
    op.drop_index(op.f('ix_superusers_email'), table_name='superusers')
    op.drop_table('superusers')
    # ### end Alembic commands ###
