"""added modarator title

Revision ID: 63584cb99cec
Revises: 9f18645af379
Create Date: 2024-03-18 12:47:00.254051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63584cb99cec'
down_revision: Union[str, None] = '9f18645af379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_moderator')
    # ### end Alembic commands ###
